version: '2'
services:
    nginx:
        build: ./docker/nginx
        ports:
            - '8888:80'
            - '4430:443'
        depends_on:
            - php
        volumes:
            - ./web:/usr/share/nginx/html
    php:
        build: ./docker/php
        depends_on:
            - database
        volumes:
            - ./web:/var/html/www
    database:
        build: ./docker/database
        volumes:
            - db:/var/lib/mysql
volumes:
    db:
